spring:
  application:
    name: api
  config:
    import: optional:configserver:http://localhost:9090
  profiles:
    active: development
  cloud:
    config:
      retry:
        initial-interval: 5000
        max-attempts: 8
        max-interval: 40000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: "*"